### ISSUE TITLE
Release version 2.0

### ISSUE THREAD

**Issue by heuermh** [heuermh/velocity-cli#3]

**Comment by heuermh** [comment]
Hello @rkraneis @sveldhuisen @fllaca, I noticed your downstream forks have commits that haven't been pull requested back here.  I'm about to cut a new release based on Velocity version 2.0, as version 1.7 has security issues (CVE-2015-6420, CVE-2017-15708).  Is there anything you'd like to move back upstream?  Thanks in advance!

**Comment by sveldhuisen** [comment]
Hello Michael,

my changes are merged with @rkraneis fork. I have added support for Velocity Resource Loader Paths so that you can use '#parse' inside Velocity templates. Also I updated the readme to reflect this new functionality. I'm not aware of any outstanding commits that haven't been pull requested. I hope that rkraneis will do I pull request.

**Comment by sveldhuisen** [comment]
FYI the pull request that is merged:

https://github.com/rkraneis/velocity-cli/pull/1

**Comment by rkraneis** [comment]
Hello Micheal,

The PR won't apply cleanly (and we probably have to check which features are interesting enough to upstream). I guess we can discuss that on the PR?

**Comment by heuermh** [comment]
This is great, thank you!  I'll go through the commits in the PR and see what makes sense to merge as-is and which to adapt (e.g. all the logging stuff has been changed in Velocity 2.0).

**Comment by rkraneis** [comment]
Thank you for the initial work ;-)
Yes, cherry-picking into your current branch might then actually be the best option.

**Comment by sveldhuisen** [comment]
Thanks guys, just let me know if you need any further assistance :)

**Comment by heuermh** [comment]
Fixed by commit 94aecb8cd7fc28028f6ca37ac628a84a7c66259c
